# General parameters
batch_size: 1
num_workers: 1
log_freq: 100
num_epochs: 100
world_size: 8
past_length: 5
pred_length: 6

# Dataset
dataset: motion_dataset
train_datafile:
  # root_dir: '/data/guifeng/traject_model/train_dataset_vectornet'
  root_dir: '/data/jerome.zhou/nuscenes/train'
val_datafile:
  # root_dir: '/data/guifeng/traject_model/val_dataset_vectornet'
  root_dir: '/data/jerome.zhou/nuscenes/val'



# Model parameters
# Encoder parameters
encoder_type: 'motionformer'
encoder_args:
  use_img: False
  backbone: 'resnet50'
  train_backbone: True
  return_interm_layer: False
  dilation: True
  bev_feature_size: 14
  hidden_size: 256
  depth: 3
  use_subgraph: False

# Aggregator parameters
aggregator_type: 'spatial_aggregator'
aggregator_args:
  hidden_size: 128


# Decoder parameters
decoder_type: 'motion_mtp'
decoder_args:
  hidden_size: 256
  in_features: 128 + 128
  pred_length: 6
  pred_num: 6
  pred_feature: 2


# Optimizer parameters
optim_args:
  lr: 0.0001


losses: ['motion_loss']
loss_weights: [1]
loss_args:
  -

tr_metrics: ['motion_loss']
tr_metric_args:
  -

val_metrics: ['motion_loss']
val_metric_args:
  -
